steps:
# Étape 1: Construit l'image avec Buildpacks en spécifiant Python 3.11
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - 'build'
    - 'gcr.io/$PROJECT_ID/agent-starter-pack-viize:latest'
    - '--builder=gcr.io/buildpacks/builder:v1'
    - '--path=.' # Assurez-vous que l'application FastAPI est à la racine du dépôt, sinon ajustez (ex: '--path=app')
  env:
    - 'GOOGLE_RUNTIME=python311'
    - 'GOOGLE_ENTRYPOINT=uvicorn app.server:app --host 0.0.0.0 --port 8080'

# Étape 2: Déploie l'image sur Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'agent-starter-pack-viize' # <-- NOM DU SERVICE CORRIGÉ POUR CORRESPONDRE AU DÉPÔT ET AU FRONTEND VERCEL
    - '--image=gcr.io/$PROJECT_ID/agent-starter-pack-viize:latest'
    - '--region=us-central1' # <-- RÉGION CORRIGÉE POUR ÊTRE us-central1
    - '--platform=managed'
    - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
  
