steps:
# Étape 1: Construit l'image avec Buildpacks en spécifiant Python 3.11
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - 'build'
    - 'gcr.io/$PROJECT_ID/agent-starter-pack-viize:latest'
    - '--builder=gcr.io/buildpacks/builder:v1'
    - '--path=.' # Le point de départ pour le Buildpack (souvent la racine)
    - '--buildpack=gcr.io/buildpacks/google_cloud_buildpacks/python/setup:latest' # <-- AJOUTEZ CETTE LIGNE
  env:
    - 'GOOGLE_RUNTIME=python311'
    - 'GOOGLE_ENTRYPOINT=uvicorn app.server:app --host 0.0.0.0 --port 8080'

# Étape 2: Déploie l'image sur Cloud Run (pas de changement ici, c'est déjà bon)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'viize-backend'
    - '--image=gcr.io/$PROJECT_ID/agent-starter-pack-viize:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
  
