steps:
- name: gcr.io/cloud-builders/docker
  args: ['build',
         '-t','gcr.io/$PROJECT_ID/agent-starter-pack-viize:${BUILD_ID}',
         '-t','gcr.io/$PROJECT_ID/agent-starter-pack-viize:latest',
         '.']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/agent-starter-pack-viize:${BUILD_ID}']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/agent-starter-pack-viize:latest']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - agent-starter-pack-viize
    - --image=gcr.io/$PROJECT_ID/agent-starter-pack-viize:${BUILD_ID}
    - --region=europe-west1
    - --allow-unauthenticated
    - --platform=managed
images:
- gcr.io/$PROJECT_ID/agent-starter-pack-viize:${BUILD_ID}
- gcr.io/$PROJECT_ID/agent-starter-pack-viize:latest
options:
  logging: CLOUD_LOGGING_ONLY
