steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','gcr.io/$PROJECT_ID/agent-gateway:$SHORT_SHA','-f','Dockerfile.gateway','.']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/agent-gateway:$SHORT_SHA']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    - gcloud
    - run
    - deploy
    - agent-gateway
    - --image=gcr.io/$PROJECT_ID/agent-gateway:$SHORT_SHA
    - --platform=managed
    - --region=$_REGION
    - --allow-unauthenticated
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,VERTEX_LOCATION=$_REGION,GEMINI_MODEL=gemini-2.5-flash
substitutions:
  _REGION: us-central1
options:
  logging: CLOUD_LOGGING_ONLY
